version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /src/frontend
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /tests/frontend
    schedule:
      interval: weekly
